apiVersion: v1
kind: Service
metadata:
  name: hello-arc-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-arc
  externalIPs:
  - 192.168.0.78
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

